function keywordize(id, label) {
  return [...new Set([label.toLowerCase(), id.replaceAll('-', ' '), ...id.split('-').filter((part) => part.length > 2)])]
}

function domain(id, label, keywords, skills) {
  return {
    id,
    label,
    keywords,
    skills: skills.map(([skillId, skillLabel]) => [skillId, skillLabel, keywordize(skillId, skillLabel)]),
  }
}

export const apChemistryTutorDomains = [
  domain('atomic-structure-properties', 'Atomic Structure and Properties',
    ['atom', 'atomic structure', 'electron', 'periodic', 'mole', 'mass spectrum'], [
      ['moles-molar-mass', 'Moles and Molar Mass'],
      ['mass-spectra-elements', 'Mass Spectra of Elements'],
      ['elemental-composition-pure-substances', 'Elemental Composition of Pure Substances'],
      ['composition-mixtures', 'Composition of Mixtures'],
      ['atomic-structure-electron-configuration', 'Atomic Structure and Electron Configuration'],
      ['photoelectron-spectroscopy', 'Photoelectron Spectroscopy'],
      ['periodic-trends', 'Periodic Trends'],
      ['valence-electrons-ionic-compounds', 'Valence Electrons and Ionic Compounds'],
    ]),
  domain('compound-structure-properties', 'Compound Structure and Properties',
    ['bond', 'lewis', 'molecular geometry', 'ionic', 'covalent', 'compound structure'], [
      ['types-chemical-bonds', 'Types of Chemical Bonds'],
      ['intramolecular-force-potential-energy', 'Intramolecular Force and Potential Energy'],
      ['structure-ionic-solids', 'Structure of Ionic Solids'],
      ['structure-metals-alloys', 'Structure of Metals and Alloys'],
      ['lewis-diagrams', 'Lewis Diagrams'],
      ['resonance-formal-charge', 'Resonance and Formal Charge'],
      ['vsepr-hybridization', 'VSEPR and Hybridization'],
    ]),
  domain('properties-substances-mixtures', 'Properties of Substances and Mixtures',
    ['intermolecular', 'gas', 'solution', 'mixture', 'spectroscopy', 'solubility'], [
      ['intermolecular-interparticle-forces', 'Intermolecular and Interparticle Forces'],
      ['properties-solids', 'Properties of Solids'],
      ['solids-liquids-gases', 'Solids, Liquids, and Gases'],
      ['ideal-gas-law', 'Ideal Gas Law'],
      ['kinetic-molecular-theory', 'Kinetic Molecular Theory'],
      ['deviation-ideal-gas-law', 'Deviation from Ideal Gas Law'],
      ['solutions-mixtures', 'Solutions and Mixtures'],
      ['representations-solutions', 'Representations of Solutions'],
      ['separation-solutions-mixtures', 'Separation of Solutions and Mixtures'],
      ['solubility', 'Solubility'],
      ['spectroscopy-electromagnetic-spectrum', 'Spectroscopy and the Electromagnetic Spectrum'],
      ['properties-photons', 'Properties of Photons'],
      ['beer-lambert-law', 'Beer-Lambert Law'],
    ]),
  domain('chemical-reactions', 'Chemical Reactions',
    ['reaction', 'stoichiometry', 'titration', 'net ionic', 'precipitation', 'redox'], [
      ['introduction-reactions', 'Introduction for Reactions'],
      ['net-ionic-equations', 'Net Ionic Equations'],
      ['representations-reactions', 'Representations of Reactions'],
      ['physical-chemical-changes', 'Physical and Chemical Changes'],
      ['stoichiometry', 'Stoichiometry'],
      ['introduction-titration', 'Introduction to Titration'],
      ['types-chemical-reactions', 'Types of Chemical Reactions'],
      ['introduction-acid-base-reactions', 'Introduction to Acid-Base Reactions'],
      ['oxidation-reduction-reactions', 'Oxidation-Reduction (Redox) Reactions'],
    ]),
  domain('kinetics', 'Kinetics',
    ['kinetics', 'reaction rate', 'rate law', 'activation energy', 'mechanism'], [
      ['reaction-rates', 'Reaction Rates'],
      ['introduction-rate-law', 'Introduction to Rate Law'],
      ['concentration-changes-time', 'Concentration Changes Over Time'],
      ['elementary-reactions', 'Elementary Reactions'],
      ['collision-model', 'Collision Model'],
      ['reaction-energy-profile', 'Reaction Energy Profile'],
      ['introduction-reaction-mechanisms', 'Introduction to Reaction Mechanisms'],
      ['reaction-mechanism-rate-law', 'Reaction Mechanism and Rate Law'],
      ['pre-equilibrium-approximation', 'Pre-Equilibrium Approximation'],
      ['multistep-reaction-energy-profile', 'Multistep Reaction Energy Profile'],
      ['catalysis', 'Catalysis'],
    ]),
  domain('thermochemistry', 'Thermochemistry',
    ['thermochemistry', 'enthalpy', 'calorimetry', 'heat', 'hess law', 'bond enthalpy'], [
      ['endothermic-exothermic-processes', 'Endothermic and Exothermic Processes'],
      ['energy-diagrams', 'Energy Diagrams'],
      ['heat-transfer-thermal-equilibrium', 'Heat Transfer and Thermal Equilibrium'],
      ['heat-capacity-calorimetry', 'Heat Capacity and Calorimetry'],
      ['energy-phase-changes', 'Energy of Phase Changes'],
      ['introduction-enthalpy-reaction', 'Introduction to Enthalpy of Reaction'],
      ['bond-enthalpies', 'Bond Enthalpies'],
      ['enthalpy-formation', 'Enthalpy of Formation'],
      ['hess-law', "Hess's Law"],
    ]),
  domain('equilibrium', 'Equilibrium',
    ['equilibrium', 'le chatelier', 'equilibrium constant', 'reaction quotient', 'ksp'], [
      ['introduction-equilibrium', 'Introduction to Equilibrium'],
      ['direction-reversible-reactions', 'Direction of Reversible Reactions'],
      ['reaction-quotient-equilibrium-constant', 'Reaction Quotient and Equilibrium Constant'],
      ['calculating-equilibrium-constant', 'Calculating the Equilibrium Constant'],
      ['magnitude-equilibrium-constant', 'Magnitude of the Equilibrium Constant'],
      ['properties-equilibrium-constant', 'Properties of the Equilibrium Constant'],
      ['calculating-equilibrium-concentrations', 'Calculating Equilibrium Concentrations'],
      ['representations-equilibrium', 'Representations of Equilibrium'],
      ['introduction-le-chatelier-principle', "Introduction to Le Chatelier's Principle"],
      ['reaction-quotient-le-chatelier-principle', "Reaction Quotient and Le Chatelier's Principle"],
      ['introduction-solubility-equilibria', 'Introduction to Solubility Equilibria'],
      ['common-ion-effect', 'Common-Ion Effect'],
    ]),
  domain('acids-bases', 'Acids and Bases',
    ['acid', 'base', 'ph', 'pka', 'buffer', 'neutralization', 'carbonate', 'hydroxide', 'conjugate acid', 'conjugate base'], [
      ['introduction-acids-bases', 'Introduction to Acids and Bases'],
      ['ph-poh-strong-acids-bases', 'pH and pOH of Strong Acids and Bases'],
      ['weak-acid-base-equilibria', 'Weak Acid and Base Equilibria'],
      ['acid-base-reactions-buffers', 'Acid-Base Reactions and Buffers'],
      ['acid-base-titrations', 'Acid-Base Titrations'],
      ['molecular-structure-acids-bases', 'Molecular Structure of Acids and Bases'],
      ['ph-pka', 'pH and pKa'],
      ['properties-buffers', 'Properties of Buffers'],
      ['henderson-hasselbalch-equation', 'Henderson-Hasselbalch Equation'],
      ['buffer-capacity', 'Buffer Capacity'],
      ['ph-solubility', 'pH and Solubility'],
    ]),
  domain('thermodynamics-electrochemistry', 'Thermodynamics and Electrochemistry',
    ['thermodynamics', 'entropy', 'gibbs', 'electrochemistry', 'galvanic', 'electrolytic', 'cell potential'], [
      ['introduction-entropy', 'Introduction to Entropy'],
      ['absolute-entropy-entropy-change', 'Absolute Entropy and Entropy Change'],
      ['gibbs-free-energy-thermodynamic-favorability', 'Gibbs Free Energy and Thermodynamic Favorability'],
      ['thermodynamic-kinetic-control', 'Thermodynamic and Kinetic Control'],
      ['free-energy-equilibrium', 'Free Energy and Equilibrium'],
      ['free-energy-dissolution', 'Free Energy of Dissolution'],
      ['coupled-reactions', 'Coupled Reactions'],
      ['galvanic-electrolytic-cells', 'Galvanic (Voltaic) and Electrolytic Cells'],
    ]),
]
